name: porous_flow
channels:
    - defaults
dependencies:
    - python>=3.11
    - numpy
    - scipy
    - conda-forge::fipy
    - cantera::cantera
    - pip
    - pip:
        - git+https://github.com/ZBT-Tools/pemfc-core.git@fluid_extension#egg=pemfc