name: porous_flow_env
channels:
    - conda-forge
dependencies:
    - python>=3.10
    - numpy
    - scipy
    - matplotlib
    - fipy
    - pip
    - pip:
        - git+https://github.com/ZBT-Tools/pemfc-core.git@master#egg=pemfc